#! usr/bin/env node
import inquirer from "inquirer";
let personName = "Syeda Ashna Ghazanfar";
console.log(` ^^^ Welcome to number guessing game generated by ${personName} ^^^`);
let randomNumber = Math.floor(Math.random() * 5 + 1);
let guessedNumber = await inquirer.prompt([
    {
        name: "guessedByUser",
        type: "number",
        message: "Please enter you guessed number to proceed further (limit: from 1 to five)",
    }
]);
if (guessedNumber.guessedByUser === randomNumber) {
    console.log(`You guessed the correct number!,the number was ${randomNumber}`);
}
else {
    console.log(`Opps! you guessed it wrong, the correct number was ${randomNumber}`);
}
console.log("   Thank you for playing hope you enjoyed!");
